openapi: 3.0.3
info:
  title: Location Navigation Service API
  version: 1.0.0
  description: Geospatial queries, location tracking, and area management
servers:
  - url: http://localhost:8090
    description: Local development
paths:
  /api/v1/locations:
    get:
      summary: List locations
      tags: [Locations]
      security: [{bearerAuth: []}]
      responses:
        "200":
          description: List of locations
    post:
      summary: Create location
      tags: [Locations]
      security: [{bearerAuth: []}]
      responses:
        "201":
          description: Location created
  /api/v1/locations/{id}/areas:
    get:
      summary: Get areas within location
      tags: [Areas]
      security: [{bearerAuth: []}]
      parameters:
        - name: id
          in: path
          required: true
          schema: {type: string}
      responses:
        "200":
          description: List of areas
    post:
      summary: Create area
      tags: [Areas]
      security: [{bearerAuth: []}]
      parameters:
        - name: id
          in: path
          required: true
          schema: {type: string}
      responses:
        "201":
          description: Area created
  /api/v1/geospatial/nearby:
    post:
      summary: Find nearby entities
      tags: [Geospatial]
      security: [{bearerAuth: []}]
      responses:
        "200":
          description: Nearby entities
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
