openapi: 3.0.3
info:
  title: Mission Command Service API
  version: 1.0.0
  description: Manages missions, tactical commands, and mission chat
servers:
  - url: http://localhost:8087
    description: Local development
  - url: http://mission-command-service.platform-dev.svc.cluster.local:8087
    description: Kubernetes dev namespace
paths:
  /api/v1/missions:
    get:
      summary: List missions
      tags: [Missions]
      security: [{bearerAuth: []}]
      parameters:
        - name: status
          in: query
          schema: {type: string, enum: [active, completed, archived]}
      responses:
        '200':
          description: List of missions
          content:
            application/json:
              schema:
                type: array
                items: {$ref: '#/components/schemas/Mission'}
    post:
      summary: Create mission
      tags: [Missions]
      security: [{bearerAuth: []}]
      requestBody:
        required: true
        content:
          application/json:
            schema: {$ref: '#/components/schemas/CreateMissionRequest'}
      responses:
        '201':
          description: Mission created
          content:
            application/json:
              schema: {$ref: '#/components/schemas/Mission'}
  /api/v1/missions/{id}:
    get:
      summary: Get mission details
      tags: [Missions]
      security: [{bearerAuth: []}]
      parameters:
        - name: id
          in: path
          required: true
          schema: {type: string}
      responses:
        '200':
          description: Mission details
          content:
            application/json:
              schema: {$ref: '#/components/schemas/Mission'}
  /api/v1/missions/{id}/claim:
    post:
      summary: Claim mission
      tags: [Missions]
      security: [{bearerAuth: []}]
      parameters:
        - name: id
          in: path
          required: true
          schema: {type: string}
      requestBody:
        required: true
        content:
          application/json:
            schema: {$ref: '#/components/schemas/ClaimMissionRequest'}
      responses:
        '200':
          description: Mission claimed
  /api/v1/tactical-commands:
    get:
      summary: List tactical commands
      tags: [Tactical Commands]
      security: [{bearerAuth: []}]
      parameters:
        - name: missionId
          in: query
          schema: {type: string}
        - name: status
          in: query
          schema: {type: string}
      responses:
        '200':
          description: List of tactical commands
          content:
            application/json:
              schema:
                type: array
                items: {$ref: '#/components/schemas/TacticalCommand'}
    post:
      summary: Create tactical command
      tags: [Tactical Commands]
      security: [{bearerAuth: []}]
      requestBody:
        required: true
        content:
          application/json:
            schema: {$ref: '#/components/schemas/CreateTacticalCommandRequest'}
      responses:
        '201':
          description: Command created
          content:
            application/json:
              schema: {$ref: '#/components/schemas/TacticalCommand'}
  /api/v1/missions/{missionId}/chat:
    get:
      summary: Get mission chat history
      tags: [Mission Chat]
      security: [{bearerAuth: []}]
      parameters:
        - name: missionId
          in: path
          required: true
          schema: {type: string}
        - name: limit
          in: query
          schema: {type: integer, default: 50}
      responses:
        '200':
          description: Chat messages
          content:
            application/json:
              schema: {$ref: '#/components/schemas/MissionChatResponse'}
    post:
      summary: Send chat message
      tags: [Mission Chat]
      security: [{bearerAuth: []}]
      parameters:
        - name: missionId
          in: path
          required: true
          schema: {type: string}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [content]
              properties:
                content: {type: string}
      responses:
        '201':
          description: Message sent
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Mission:
      type: object
      required: [id, title, description, status, priority, dispatchIds, assetIds, eventIds, tags, createdAt, updatedAt]
      properties:
        id: {type: string}
        title: {type: string}
        description: {type: string}
        status: {type: string, enum: [active, completed, archived]}
        priority: {type: string}
        claimedByOperatorId: {type: string}
        claimedByOperatorName: {type: string}
        dispatchIds: {type: array, items: {type: string}}
        assetIds: {type: array, items: {type: string}}
        eventIds: {type: array, items: {type: string}}
        tags: {type: array, items: {type: string}}
        createdAt: {type: string, format: date-time}
        updatedAt: {type: string, format: date-time}
    CreateMissionRequest:
      type: object
      required: [title, description, priority, dispatchId]
      properties:
        title: {type: string}
        description: {type: string}
        priority: {type: string}
        dispatchId: {type: string}
    ClaimMissionRequest:
      type: object
      required: [operatorId, operatorName]
      properties:
        operatorId: {type: string}
        operatorName: {type: string}
    TacticalCommand:
      type: object
      properties:
        id: {type: string}
        mission_id: {type: string}
        title: {type: string}
        description: {type: string}
        category: {type: string}
        priority: {type: string}
        status: {type: string}
        source: {type: string}
    CreateTacticalCommandRequest:
      type: object
      required: [mission_id, title, description, category, priority]
      properties:
        mission_id: {type: string}
        title: {type: string}
        description: {type: string}
        category: {type: string}
        priority: {type: string}
    MissionChatResponse:
      type: object
      properties:
        messages: {type: array}
        totalCount: {type: integer}
        hasMore: {type: boolean}
